import {useEffect,useMemo,useState} from 'react'
import {Search,Sun,Moon,Rows3,LayoutGrid,Download,ChevronRight,Database,Globe2,ShieldAlert,TrendingUp,Info,ExternalLink} from 'lucide-react'
import {Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {loadCatalogue,loadHsLibrary,loadProduct,type CatalogueItem,type HsLibraryItem,type LiveProduct} from './data/live'
import {downloadPng,downloadSvg,downloadText,rowsToCsv} from './utils/download'

const money=(n:number|null|undefined)=>{if(n==null)return'—';const a=Math.abs(n),s=n<0?'−':'';if(a>=1e12)return`${s}$${(a/1e12).toFixed(2)}tn`;if(a>=1e9)return`${s}$${(a/1e9).toFixed(2)}bn`;if(a>=1e6)return`${s}$${(a/1e6).toFixed(1)}mn`;return`${s}$${a.toLocaleString(undefined,{maximumFractionDigits:0})}`}
const pct=(n:number|null|undefined,d=1)=>n==null?'—':`${n.toFixed(d)}%`;const signed=(n:number|null|undefined)=>n==null?'—':`${n>=0?'+':''}${n.toFixed(1)}%`
function Metric({label,value,sub,tone='neutral'}:{label:string,value:string,sub?:string,tone?:'neutral'|'good'|'warn'}){return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function ExportButtons({id,name}:{id:string,name:string}){return <div className="exports"><button onClick={()=>downloadPng(id,name)}>PNG</button><button onClick={()=>downloadSvg(id,name)}>SVG</button></div>}

export default function App(){
 const [product,setProduct]=useState<LiveProduct|null>(null),[catalogue,setCatalogue]=useState<CatalogueItem[]>([]),[library,setLibrary]=useState<HsLibraryItem[]>([]),[query,setQuery]=useState('847130'),[error,setError]=useState(''),[tab,setTab]=useState<'product'|'india'|'dependencies'|'methodology'>('product'),[partnerMode,setPartnerMode]=useState<'suppliers'|'destinations'>('suppliers'),[theme,setTheme]=useState(localStorage.getItem('hstat-theme')||'light'),[dense,setDense]=useState(localStorage.getItem('hstat-density')==='dense'),[focused,setFocused]=useState(false),[loading,setLoading]=useState(false)
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('hstat-theme',theme)},[theme]);useEffect(()=>{document.documentElement.dataset.density=dense?'dense':'simple';localStorage.setItem('hstat-density',dense?'dense':'simple')},[dense])
 const openHs=async(code:string)=>{const c=code.replace(/\D/g,'').slice(0,6);if(c.length!==6){setQuery(c);setFocused(true);return}try{setLoading(true);setError('');setProduct(null);const p=await loadProduct(c);setProduct(p);setQuery(c);setTab('product');setFocused(false)}catch(e){setError(e instanceof Error?e.message:String(e));setQuery(c)}finally{setLoading(false)}}
 useEffect(()=>{Promise.all([loadCatalogue(),loadHsLibrary()]).then(([c,l])=>{setCatalogue(c.products);setLibrary(l.items)});openHs('847130')},[])
 const matches=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return library.filter(x=>x.code.includes(q)||x.description.toLowerCase().includes(q)||x.tags.some(t=>t.includes(q))).sort((a,b)=>(Number(b.loaded)-Number(a.loaded))||(a.level-b.level)||a.code.localeCompare(b.code)).slice(0,12)},[query,library])
 const quick=['8471','8517','8542','8541','8507','847130'];const p=product;const partners=p?(partnerMode==='suppliers'?p.suppliers:p.destinations):[];const chartPartners=partners.slice(0,dense?10:7).map(x=>({name:x.name,share:+x.share.toFixed(2)}));const trend=p?.trend.map(t=>({year:String(t.year),imports:t.indiaImports? t.indiaImports/1e9:null,exports:t.indiaExports?t.indiaExports/1e9:null}))??[]
 const indiaRows=[...catalogue].sort((a,b)=>(b.indiaExportShare??-1)-(a.indiaExportShare??-1));const depRows=[...catalogue].sort((a,b)=>(b.largestSupplierShare??-1)-(a.largestSupplierShare??-1));
 const insights=p?[p.global.worldExportGrowthYoY!=null&&p.india.exportGrowthYoY!=null?(p.india.exportGrowthYoY>p.global.worldExportGrowthYoY?'India’s exports are growing faster than reported world exports.':'India’s export growth is trailing reported world export growth.'):null,p.india.largestSupplier&&p.india.largestSupplier.share>=50?`${p.india.largestSupplier.name} accounts for ${pct(p.india.largestSupplier.share)} of India’s imports, indicating concentrated sourcing.`:null,p.india.tradeBalance<0?`India records a ${money(Math.abs(p.india.tradeBalance))} trade deficit in this product.`:`India records a ${money(p.india.tradeBalance)} trade surplus in this product.`].filter(Boolean) as string[]:[]
 const exportTable=(kind:'suppliers'|'destinations')=>{const r=kind==='suppliers'?p?.suppliers:p?.destinations;if(!r)return;downloadText(`HS-${p?.product.hs6}-${kind}.csv`,rowsToCsv(r.map(x=>({country:x.name,iso:x.iso,value_usd:x.value,share_percent:x.share,quantity:x.quantity,unit:x.quantityUnit}))), 'text/csv')}
 return <div className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>setTab('product')}><img src="/fed-mark.png"/><span>HStat.<b>India</b></span><em>Trade Intelligence</em></button><nav>{[['product','Product Intelligence'],['india','India Position'],['dependencies','Dependencies'],['methodology','Methodology']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as typeof tab)}>{l}</button>)}</nav><div className="toggles"><button title="Toggle density" onClick={()=>setDense(!dense)}>{dense?<Rows3/>:<LayoutGrid/>}</button><button title="Toggle theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</button></div></header>
  <main>
   <section className="search-area"><div className="search-wrap"><Search/><input value={query} onFocus={()=>setFocused(true)} onChange={e=>{setQuery(e.target.value);setFocused(true)}} onKeyDown={e=>e.key==='Enter'&&openHs(query)} placeholder="Search HS code, laptop, semiconductor, router, battery…"/><button onClick={()=>openHs(query)}>Open</button>{focused&&matches.length>0&&<div className="search-results">{matches.map(x=><button key={`${x.code}-${x.level}`} onMouseDown={e=>e.preventDefault()} onClick={()=>x.level===6?openHs(x.code):(setQuery(x.code),setFocused(true))}><span><b>HS-{x.level} · {x.code}</b><em>{x.description}</em></span><i>{x.tags.slice(0,2).join(' · ')}</i><strong className={x.loaded?'loaded':''}>{x.loaded?'Data loaded':x.level===6?'Available to load':'Browse'}</strong></button>)}</div>}</div><div className="quick"><span>Quick access</span>{quick.map(x=><button key={x} onClick={()=>{setQuery(x);if(x.length===6)openHs(x);else setFocused(true)}}>{x}</button>)}</div></section>
   {loading&&<div className="notice"><Database/><span>Loading HS {query}…</span></div>}{error&&<div className="notice"><Info/><span>No loaded trade dataset is available for HS {query}.</span></div>}

   {tab==='india'&&<><section className="page-title"><div><small>INDIA POSITION</small><h1>India across loaded MeitY product lines</h1></div><p>Compare export position, share, momentum and trade scale across products already loaded into HStat.</p></section><section className="metric-grid four"><Metric label="Loaded HS-6 products" value={String(catalogue.length)}/><Metric label="Best export rank" value={indiaRows.find(x=>x.indiaExportRank)?.indiaExportRank?`#${indiaRows.find(x=>x.indiaExportRank)!.indiaExportRank}`:'—'}/><Metric label="Highest global share" value={pct(indiaRows[0]?.indiaExportShare)}/><Metric label="Fastest export growth" value={signed([...catalogue].sort((a,b)=>(b.exportGrowthYoY??-999)-(a.exportGrowthYoY??-999))[0]?.exportGrowthYoY)}/></section><article className="panel"><div className="panel-head"><div><small>COMPARATIVE POSITION</small><h3>Loaded product ranking</h3></div><button className="download" onClick={()=>downloadText('hstat-india-position.csv',rowsToCsv(indiaRows as unknown as Record<string,unknown>[]),'text/csv')}><Download/> CSV</button></div><div className="table"><div className="tr th"><span>HS-6</span><span>Product</span><span>India rank</span><span>World share</span><span>Exports</span></div>{indiaRows.map(x=><button className="tr rowbtn" key={x.hs6} onClick={()=>openHs(x.hs6)}><b>{x.hs6}</b><span>{x.description}</span><span>{x.indiaExportRank?`#${x.indiaExportRank}`:'—'}</span><span>{pct(x.indiaExportShare)}</span><span>{money(x.indiaExports)}</span></button>)}</div></article></>}

   {tab==='dependencies'&&<><section className="page-title"><div><small>DEPENDENCIES</small><h1>Import concentration monitor</h1></div><p>Prioritise products with large import exposure and concentrated sourcing.</p></section><section className="metric-grid four"><Metric label="Products monitored" value={String(depRows.length)}/><Metric label="Highest supplier share" value={pct(depRows[0]?.largestSupplierShare)} sub={depRows[0]?.largestSupplier??'—'}/><Metric label="High-concentration products" value={String(depRows.filter(x=>x.supplierConcentration==='High').length)}/><Metric label="Largest import bill" value={money([...depRows].sort((a,b)=>(b.indiaImports??0)-(a.indiaImports??0))[0]?.indiaImports)}/></section><article className="panel"><div className="panel-head"><div><small>DEPENDENCY SCREEN</small><h3>Products ranked by largest-supplier share</h3></div><button className="download" onClick={()=>downloadText('hstat-dependencies.csv',rowsToCsv(depRows as unknown as Record<string,unknown>[]),'text/csv')}><Download/> CSV</button></div><div className="table"><div className="tr th"><span>HS-6</span><span>Product</span><span>Top supplier</span><span>Supplier share</span><span>Imports</span></div>{depRows.map(x=><button className="tr rowbtn" key={x.hs6} onClick={()=>openHs(x.hs6)}><b>{x.hs6}</b><span>{x.description}</span><span>{x.largestSupplier??'—'}</span><span className={(x.largestSupplierShare??0)>=50?'warn':''}>{pct(x.largestSupplierShare)}</span><span>{money(x.indiaImports)}</span></button>)}</div></article></>}

   {tab==='methodology'&&<><section className="page-title"><div><small>METHODOLOGY</small><h1>Transparent by construction</h1></div><p>Observed statistics, derived indicators and curated relationships are kept distinct.</p></section><section className="method-grid"><article className="panel"><h3>Global comparison</h3><p>HS-6 is used internationally. HStat does not treat the newest year as complete automatically. Global totals, ranks and shares are shown only for the latest year passing coverage checks against the previous year's major reporting economies. India headline trade may therefore be newer than the global benchmark.</p></article><article className="panel"><h3>India detail</h3><p>India analysis drills into national tariff-line records when returned at 8 digits. DGFT/TradeStat remains the reference for Indian ITC(HS) nomenclature and policy treatment.</p></article><article className="panel"><h3>Concentration</h3><p><b>HHI = Σ supplier share².</b> HStat labels ≥0.25 High, 0.15–0.25 Moderate, below 0.15 Low. These are analytical thresholds, not statutory classifications.</p></article><article className="panel"><h3>Growth</h3><p>YoY compares adjacent annual values. CAGR uses the first and last available positive values in the selected period.</p></article><article className="panel"><h3>Supply chain</h3><p>Upstream/downstream links are curated product relationships. They do not assert that an observed import was physically embodied in a specific export.</p></article><article className="panel"><h3>Data quality</h3><p>Global coverage validation requires the previous-year leader, at least four of the previous top five reporters, at least 90% value coverage of the previous top 20, and at least 75% of the previous reporter count. If those checks fail, world totals, India rank and India share are withheld. Quantity and weight fields may also be estimated.</p></article></section></>}

   {tab==='product'&&p&&<><div className="crumbs"><span>World</span><ChevronRight/><span>India</span><ChevronRight/><b>HS {p.product.hs6}</b></div><section className="product-hero"><div><div className="eyebrow"><Globe2/> GLOBAL → INDIA · HS-6</div><h1>{p.product.description}</h1><p>HS {p.product.hs6} · latest annual period {p.period.latest}</p></div><div className="source-chip"><Database/><span>UN Comtrade</span><b>{p.period.latest}</b></div></section>
    <section className="split-title"><div><span>01</span><h2>World position</h2></div><p>Market scale, leaders and India's relative position.</p></section><section className="metric-grid six"><Metric label={`Reported world exports${p.global.comparisonYear?` (${p.global.comparisonYear})`:''}`} value={money(p.global.reportedWorldExports)}/><Metric label={`World export growth${p.global.comparisonYear?` (${p.global.comparisonYear} YoY)`:''}`} value={signed(p.global.worldExportGrowthYoY)}/><Metric label={`Global export leader${p.global.comparisonYear?` (${p.global.comparisonYear})`:''}`} value={p.global.leader??'—'} sub={pct(p.global.leaderShare)}/><Metric label={`India export rank${p.global.comparisonYear?` (${p.global.comparisonYear})`:''}`} value={p.global.indiaExportRank?`#${p.global.indiaExportRank}`:'—'}/><Metric label={`India export share${p.global.comparisonYear?` (${p.global.comparisonYear})`:''}`} value={pct(p.global.indiaExportShare)}/><Metric label={`India import rank${p.global.comparisonYear?` (${p.global.comparisonYear})`:''}`} value={p.global.indiaImportRank?`#${p.global.indiaImportRank}`:'—'}/></section>
    {p.global.coverageStatus!=='validated'&&<div className="notice"><ShieldAlert/><span>{p.global.coverageNote}</span></div>}<section className="country-grid"><article className="panel"><div className="panel-head"><div><small>TOP 10 · {p.global.comparisonYear??'WITHHELD'}</small><h3>Exporting economies</h3></div></div>{p.global.topExporters?.map(x=><div className={`country-row ${x.name==='India'?'india':''}`} key={x.code}><b>#{x.rank}</b><span>{x.name}</span><strong>{money(x.value)}</strong><em>{pct(x.share)}</em></div>)}</article><article className="panel"><div className="panel-head"><div><small>TOP 10 · {p.global.comparisonYear??'WITHHELD'}</small><h3>Importing economies</h3></div></div>{p.global.topImporters?.map(x=><div className={`country-row ${x.name==='India'?'india':''}`} key={x.code}><b>#{x.rank}</b><span>{x.name}</span><strong>{money(x.value)}</strong><em>{pct(x.share)}</em></div>)}</article></section>
    <section className="split-title"><div><span>02</span><h2>India position</h2></div><p>Trade scale, momentum and policy-relevant signals.</p></section><section className="metric-grid six"><Metric label="India imports" value={money(p.india.imports)}/><Metric label="India exports" value={money(p.india.exports)} tone="good"/><Metric label="Trade balance" value={money(p.india.tradeBalance)} tone={p.india.tradeBalance<0?'warn':'good'}/><Metric label="Import growth" value={signed(p.india.importGrowthYoY)}/><Metric label="Export growth" value={signed(p.india.exportGrowthYoY)}/><Metric label="5Y export CAGR" value={pct(p.india.exportCAGR)}/></section><section className="insight-grid"><article className="panel insight"><div className="panel-head"><div><small>PERSPECTIVE</small><h3>What stands out</h3></div><TrendingUp/></div>{insights.map((x,i)=><p key={i}>{x}</p>)}</article><article className="panel insight"><div className="panel-head"><div><small>DEPENDENCY</small><h3>Sourcing concentration</h3></div><ShieldAlert/></div><p><b>{p.india.largestSupplier?.name??'—'}</b> is the largest source at <b>{pct(p.india.largestSupplier?.share)}</b>.</p><p>Top three suppliers account for <b>{pct(p.india.supplierConcentration.top3Share)}</b>; HHI is <b>{p.india.supplierConcentration.hhi?.toFixed(3)??'—'}</b> ({p.india.supplierConcentration.level??'—'}).</p></article></section>
    <section className="chart-grid"><article className="panel" id="trade-trend"><div className="panel-head"><div><small>TRADE TRAJECTORY</small><h3>India imports & exports</h3></div><ExportButtons id="trade-trend" name={`HS-${p.product.hs6}-trade-trend`}/></div><ResponsiveContainer width="100%" height={dense?330:260}><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={(v)=>[`$${Number(v ?? 0).toFixed(2)}bn`]}/><Area type="monotone" dataKey="imports" strokeWidth={2} fillOpacity={0}/><Area type="monotone" dataKey="exports" strokeWidth={2} fillOpacity={0}/></AreaChart></ResponsiveContainer></article><article className="panel" id="partner-chart"><div className="panel-head"><div><small>PARTNER NETWORK</small><h3>{partnerMode==='suppliers'?'Import sources':'Export markets'}</h3></div><div className="head-actions"><ExportButtons id="partner-chart" name={`HS-${p.product.hs6}-${partnerMode}`}/><button className="download" onClick={()=>exportTable(partnerMode)}><Download/> CSV</button></div></div><div className="seg"><button className={partnerMode==='suppliers'?'active':''} onClick={()=>setPartnerMode('suppliers')}>Sources</button><button className={partnerMode==='destinations'?'active':''} onClick={()=>setPartnerMode('destinations')}>Destinations</button></div><ResponsiveContainer width="100%" height={dense?330:260}><BarChart data={chartPartners} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" unit="%"/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="share" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></article></section>
    <section className="split-title"><div><span>03</span><h2>India 8-digit detail</h2></div><p>National tariff-line view beneath the globally comparable HS-6 code.</p></section>{p.india8.available?<article className="panel"><div className="panel-head"><div><small>INDIA TARIFF LINES</small><h3>{p.india8.lines.length} lines under HS {p.product.hs6}</h3></div><div className="head-actions"><button className="download" onClick={()=>downloadText(`HS-${p.product.hs6}-india8.csv`,rowsToCsv(p.india8.lines as unknown as Record<string,unknown>[]),'text/csv')}><Download/> CSV</button><button className="download" onClick={()=>downloadText(`HS-${p.product.hs6}-india8.json`,JSON.stringify(p.india8.lines,null,2),'application/json')}>JSON</button></div></div><div className="table"><div className="tr hs8 th"><span>ITC/HS-8</span><span>Description</span><span>Imports</span><span>Exports</span><span>Balance</span></div>{p.india8.lines.map(x=><div className="tr hs8" key={x.code}><b>{x.code}</b><span>{x.description}</span><span>{money(x.imports)}</span><span>{money(x.exports)}</span><span>{money(x.tradeBalance)}</span></div>)}</div><p className="fine">{p.india8.note}</p></article>:<div className="notice"><Info/><span>{p.india8.note}</span></div>}
    <section className="split-title"><div><span>04</span><h2>Supply-chain context</h2></div><p>Curated relationships, kept separate from observed bilateral trade.</p></section>{p.supplyChain.available?<><p className="chain-context">{p.supplyChain.context}</p><section className="chain-grid"><article className="panel"><div className="panel-head"><div><small>UPSTREAM</small><h3>Common inputs</h3></div></div>{p.supplyChain.upstream.length?p.supplyChain.upstream.map(x=><button className="chain-item" key={x.hs} onClick={()=>x.hs.length===6&&openHs(x.hs)}><span><b>HS {x.hs}</b>{x.label}</span><em>{x.relation} · {x.confidence}</em></button>):<p className="fine">No upstream links curated yet.</p>}</article><article className="panel"><div className="panel-head"><div><small>DOWNSTREAM</small><h3>Common uses / product families</h3></div></div>{p.supplyChain.downstream.length?p.supplyChain.downstream.map(x=><button className="chain-item" key={x.hs} onClick={()=>x.hs.length===6&&openHs(x.hs)}><span><b>HS {x.hs}</b>{x.label}</span><em>{x.relation} · {x.confidence}</em></button>):<p className="fine">No downstream links curated yet.</p>}</article></section></>:<div className="notice"><Info/><span>{p.supplyChain.note}</span></div>}
    <p className="source-note">Source: UN Comtrade for trade statistics. India tariff-line nomenclature/policy should be checked against DGFT/TradeStat. <a href="https://www.fedev.org/" target="_blank">FED <ExternalLink/></a></p>
   </>}
  </main><footer><span>HStat.India</span><p>Global trade context · India position · tariff-line depth</p><div>HS-6 for global comparison · India 8-digit detail where available</div></footer>
 </div>
}
